[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_STRIPE_PUBLISHABLE_KEY"

[[redirects]]
  from = "/api/stripe/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200
  force = true

[[redirects]]
  from = "/api/stripe/checkout-session/:sessionId"
  to = "/.netlify/functions/checkout-session/:sessionId"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
